### ISSUE TITLE
How to mention the prometheus server IP address

### ISSUE THREAD

**Issue by Vishal2696** [SpencerMalone/logstash-output-prometheus#7]
How do we mention prometheus server's IP address if it is running in a separate server? Moreover if it is indeed running in the same server is it not needed to mention localhost:portno somewhere in the configuration? Any reference links also would suffice.

**Comment by SpencerMalone** [comment]
This is based on the "exporter" prometheus model, so logstash serves a web page with the metrics, and you actually point prometheus at that logstash page, instead of pointing logstash at prometheus. The configuration definition for prometheus scrapes is found @ https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config, but I recommend watching https://www.youtube.com/watch?v=WUkNnY65htQ&feature=youtu.be&t=55 for an easier to grok overview.
